### ISSUE TITLE
colors in console

### ISSUE THREAD

**Issue by Interleace** [The-Crown-Studios/MinestomLauncher#3]
When building using mvn color resolution in console is broken

2024-04-15 23:09:05 [main] com.thecrownstudios.minestomlauncher.Main.main()
INFO: Hello world!
[main] INFO com.thecrownstudios.minestomlauncher.MinestomLauncher - Starting Mines

§c§l■§r §c§l■§r §c§l■§r
§c§l■§r §c§l■§r §c§l■§f   MINESTOM LAUNCHER§r §7§o1.2.4§r
§c§l■§r §c§l■§r §c§l■§r

 §7§l▸§r §7os info: §fLinux§7, §f5.18.16-zen1-x86_64§7 - §famd64§r
 §7§l▸§r §7java info: §f21.0.1§7 - §fEclipse Adoptium§7, §fhttps://adoptium.net/§r
 §7§l▸§r §7commit: §f97b7f61def761306323fdde69d42b0aca859913e§r
 §7§l▸§r §7version: §f1.20.4§7 - §f765§r

[main] INFO net.minestom.server.ServerProcessImpl - Starting Minestom server.
[main] INFO net.minestom.server.ServerProcessImpl - Minestom server started succes
[main] INFO com.thecrownstudios.minestomlauncher.MinestomLauncher - Server launch

 §7§l▸§r §7config location: §fserver.json§7, §floaded from existing file§r
 §7§l▸§r §7server address: §f127.0.0.1§7:§f25565§7, §funder no proxy§r
 §7§l▸§r §7tps: §f20§7, chunk distance: §f8§7, entity distance: §f6§r

§7 Server started in §f1.149§7s§r

**My logging related dependencies inside pom**

		
		<dependency>
			<groupId>org.tinylog</groupId>
			<artifactId>tinylog-impl</artifactId>
			<version>2.7.0</version>
			<scope>test</scope>
		</dependency>

		
		<dependency>
			<groupId>org.tinylog</groupId>
			<artifactId>slf4j-tinylog</artifactId>
			<version>2.7.0</version>
			<scope>test</scope>
		</dependency>

		
		<dependency>
			<groupId>org.tinylog</groupId>
			<artifactId>tinylog</artifactId>
			<version>1.3.6</version>
		</dependency>

		
		<dependency>
			<groupId>org.tinylog</groupId>
			<artifactId>slf4j-binding</artifactId>
			<version>1.3.6</version>
		</dependency>

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-simple</artifactId>
			<version>2.0.9</version>
			<scope>runtime</scope>
		</dependency>

**Comment by xGab0** [comment]
Hi, sorry for the late response. I'm working on a new Terminal implementation that hopefully will fix this issue.

**Comment by xGab0** [comment]
@Interleace After almost a year I'm happy to announce that I fixed the bug in the latest release, not everything is completely done yet but at least the colors will work again!

(sorry for waiting)
